title: Prairie Fire Glass
description: "Prairie Fire Glass is a professional glassworking studio and gallery in Monticello, Illinois."
url: "http://prairiefireglass.com"

destination: public
exclude: [public, Rakefile, README.md]

permalink: /writing/:title/
markdown: kramdown
highlighter: pygments

sass:
  style:    :compressed
  sass_dir: assets/stylesheets
